services:
  db:
    image: postgres:15
    container_name: gp_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gp_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gp_pass}
      POSTGRES_DB: ${POSTGRES_DB:-gp_db}
    ports:
      - "5432:5432"
    volumes:
      - gp_data:/var/lib/postgresql/data
    networks:
      - gp-net
  pgadmin:
    image: dpage/pgadmin4
    container_name: page_admin
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=1234'
      - 'PGADMIN_CONFIG_SERVER_MOD=False'
    volumes:
      - gp_data:/var/lib/postgresql/data
    networks:
      - gp-net
    ports:
      - '5050:80'

  backend:
    build: ./
    container_name: gp_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://gp_user:gp_pass@db:5432/gp_db
    volumes:
      - ./:/app
    networks:
      - gp-net
    depends_on:
      - db
      - pgadmin
    command: >
      bash -c  "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  gp_data:
networks:
  gp-net:
    driver: bridge
